// Schema barrel — re-export all tables so drizzle client gets full type info
// and drizzle-kit can discover all schemas in one import
export * from '@/src/infra/db/schema/costs.drizzle-schema'
export * from '@/src/infra/db/schema/fuel-consumption-records.drizzle-schema'
export * from '@/src/infra/db/schema/fuel-logs.drizzle-schema'
export * from '@/src/infra/db/schema/fuel-price-records.drizzle-schema'
export * from '@/src/infra/db/schema/fuel-types.drizzle-schema'
export * from '@/src/infra/db/schema/goals.drizzle-schema'
export * from '@/src/infra/db/schema/maintenances.drizzle-schema'
export * from '@/src/infra/db/schema/mileage-records.drizzle-schema'
export * from '@/src/infra/db/schema/planned-absences.drizzle-schema'
export * from '@/src/infra/db/schema/profit-goals.drizzle-schema'
export * from '@/src/infra/db/schema/profits.drizzle-schema'
export * from '@/src/infra/db/schema/reminders.drizzle-schema'
export * from '@/src/infra/db/schema/special-days.drizzle-schema'
export * from '@/src/infra/db/schema/trip-offer-records.drizzle-schema'
export * from '@/src/infra/db/schema/trip-platforms.drizzle-schema'
export * from '@/src/infra/db/schema/trips.drizzle-schema'
export * from '@/src/infra/db/schema/user-settings.drizzle-schema'
export * from '@/src/infra/db/schema/users.drizzle-schema'
export * from '@/src/infra/db/schema/vehicle-types.drizzle-schema'
export * from '@/src/infra/db/schema/vehicles.drizzle-schema'
export * from '@/src/infra/db/schema/work-sessions.drizzle-schema'
